export interface Project {
  id: string;
  title: string;
  category: string;
  year: string;
  image: string;
  description: string;
  tier: 'S' | 'A' | 'B';
  tech: string[];
  github?: string;
  live?: string;
  status: 'completed' | 'in-progress' | 'planned';
  stars?: number;
}

export const PROJECTS: Project[] = [
  // ===== S-TIER: FLAGSHIP =====
  {
    id: 'nvidia-ai-pipeline',
    title: 'NVIDIA AI Pipeline',
    category: 'AI / Infrastructure',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200',
    description: 'Multi-model AI pipeline orchestrating 8+ NVIDIA NIM models for code review, security auditing, translation, and PII detection. Sequential + parallel execution with fallback chains and budget controls.',
    tier: 'S',
    tech: ['TypeScript', 'NVIDIA NIM', 'Vercel', 'Express', 'OpenAI API'],
    github: 'https://github.com/febrits/nvidia-ai-pipeline',
    live: 'https://nvidia-ai-pipeline.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'agent-swarm-dashboard',
    title: 'Agent Swarm Dashboard',
    category: 'AI / Dashboard',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=1200',
    description: 'Real-time multi-agent monitoring dashboard. Spawn, steer, and track AI agents with WebSocket live updates. Zero external Go dependencies — stdlib only.',
    tier: 'S',
    tech: ['Go', 'WebSocket', 'Vercel', 'Serverless'],
    github: 'https://github.com/febrits/agent-swarm-dashboard',
    live: 'https://agent-swarm-dashboard-eight.vercel.app',
    status: 'completed',
    stars: 0,
  },
  {
    id: 'portfolio',
    title: 'Portfolio 2026',
    category: 'Portfolio',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&q=80&w=1200',
    description: 'Personal portfolio website showcasing 40+ projects. Cyberpunk-themed with glassmorphism, Framer Motion animations, and real-time GitHub stats.',
    tier: 'S',
    tech: ['React 19', 'TypeScript', 'Tailwind CSS v4', 'Framer Motion', 'Vite'],
    github: 'https://github.com/febrits/febrits.github.io',
    live: 'https://febrits.github.io',
    status: 'completed',
    stars: 5,
  },

  // ===== A-TIER: ADVANCED =====
  {
    id: 'url-shortener-go',
    title: 'URL Shortener Go',
    category: 'Backend / Go',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=1200',
    description: 'Fast URL shortener microservice written in Go. REST API with click tracking, rate limiting, and redirect management. Deployed on Vercel.',
    tier: 'A',
    tech: ['Go', 'REST API', 'Vercel', 'Serverless'],
    github: 'https://github.com/febrits/url-shortener-go',
    live: 'https://url-shortener-go.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'filevault',
    title: 'FileVault',
    category: 'File Manager',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=1200',
    description: 'Modern file manager with drag & drop upload, grid/list view, search, preview pane, and bulk operations. Organize files with folders and tags.',
    tier: 'A',
    tech: ['React 19', 'TypeScript', 'Tailwind CSS', 'Vite'],
    github: 'https://github.com/febrits/filevault',
    live: 'https://filevault-amber.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'deploybot',
    title: 'DeployBot',
    category: 'DevOps',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&q=80&w=1200',
    description: 'One-click deploy dashboard. Connect GitHub repos, manage deployments, track build history, and configure environment variables. Vercel + GitHub integration.',
    tier: 'A',
    tech: ['React 19', 'TypeScript', 'GitHub API', 'Vercel API'],
    github: 'https://github.com/febrits/deploybot',
    live: 'https://deploybot.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'authkit',
    title: 'AuthKit',
    category: 'Authentication',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=1200',
    description: 'Full authentication service with OAuth 2.0, JWT token management, session revocation, and role-based access control. Rate limiting + brute-force protection.',
    tier: 'A',
    tech: ['React 19', 'TypeScript', 'JWT', 'OAuth 2.0'],
    github: 'https://github.com/febrits/authkit',
    live: 'https://authkit-sepia.vercel.app',
    status: 'completed',
    stars: 0,
  },
  {
    id: 'datalens',
    title: 'DataLens',
    category: 'Data Analytics',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
    description: 'Data visualization dashboard with CSV/JSON upload, interactive charts (bar, line, pie, scatter), real-time filtering, and exportable dashboards.',
    tier: 'A',
    tech: ['React 19', 'TypeScript', 'Chart.js', 'D3.js'],
    github: 'https://github.com/febrits/datalens',
    live: 'https://datalens-one.vercel.app',
    status: 'completed',
    stars: 1,
  },

  // ===== B-TIER: TOOLS & APPS =====
  {
    id: 'invoicekit',
    title: 'InvoiceKit',
    category: 'Freelance Tool',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=1200',
    description: 'Professional invoice generator with line items, auto-calculations, tax support, and print-ready preview. Track paid/unpaid status.',
    tier: 'B',
    tech: ['React 19', 'TypeScript', 'Tailwind CSS', 'Vite'],
    github: 'https://github.com/febrits/invoicekit',
    live: 'https://invoicekit-olive.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'taskflow',
    title: 'TaskFlow',
    category: 'Productivity',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&q=80&w=1200',
    description: 'Trello-inspired Kanban project management with drag-and-drop boards, custom columns, task priorities, and real-time progress tracking.',
    tier: 'B',
    tech: ['React 19', 'TypeScript', '@dnd-kit', 'Tailwind CSS'],
    github: 'https://github.com/febrits/taskflow',
    live: 'https://taskflow-livid-mu.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'devblog',
    title: 'DevBlog',
    category: 'Blog Platform',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=1200',
    description: 'Full-featured blog platform with post listing, tag filtering, search, and clean dark theme. Markdown-ready with responsive design.',
    tier: 'B',
    tech: ['React 19', 'TypeScript', 'React Router', 'Tailwind CSS'],
    github: 'https://github.com/febrits/devblog',
    live: 'https://devblog-three-ochre.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'file-processor-rust',
    title: 'File Processor Rust',
    category: 'CLI / Rust',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?auto=format&fit=crop&q=80&w=1200',
    description: 'High-performance CLI tool for file processing in Rust. Batch operations with parallel execution and minimal memory footprint.',
    tier: 'B',
    tech: ['Rust', 'CLI', 'Performance'],
    github: 'https://github.com/febrits/file-processor-rust',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'habitgrid',
    title: 'HabitGrid',
    category: 'Productivity',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&q=80&w=1200',
    description: 'Habit tracker with GitHub-style contribution grid, streak tracking, completion statistics, and daily toggle. Visual consistency calendar.',
    tier: 'B',
    tech: ['React 19', 'TypeScript', 'Tailwind CSS', 'Vite'],
    github: 'https://github.com/febrits/habitgrid',
    live: 'https://habitgrid-eight.vercel.app',
    status: 'completed',
    stars: 1,
  },
  {
    id: 'snapurl',
    title: 'SnapURL',
    category: 'URL Tool',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&q=80&w=1200',
    description: 'URL shortener with analytics dashboard. Generate short URLs, track clicks, view creation dates, and manage links from a clean interface.',
    tier: 'B',
    tech: ['React 19', 'TypeScript', 'Tailwind CSS', 'Vite'],
    github: 'https://github.com/febrits/snapurl',
    live: 'https://snapurl-five.vercel.app',
    status: 'completed',
    stars: 1,
  },
];
